# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lavels.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LevelsWindow(object):
    def setupUi(self, LevelsWindow):
        LevelsWindow.setObjectName("LevelsWindow")
        LevelsWindow.resize(1450, 1000)
        LevelsWindow.setStyleSheet("QMainWindow{\n"
"border-image: url(:/newPrefix/photo/fon.png);\n"
"border-position: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(LevelsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 10, 126, 119))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/home.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/home2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(480, 70, 503, 65))
        self.label.setStyleSheet("background-image: url(:/newPrefix/photo/уровни.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 320, 121, 118))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(590, 320, 121, 118))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(750, 320, 121, 118))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(910, 320, 121, 118))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 490, 121, 118))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(590, 490, 121, 118))
        self.label_7.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(910, 490, 121, 118))
        self.label_8.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(750, 490, 121, 118))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/photo/kvadrik.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(460, 344, 61, 71))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/1.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/1-2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(617, 344, 71, 71))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/2-2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(774, 344, 71, 71))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/3.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/3-2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(940, 344, 71, 71))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/4.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/4-2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(458, 514, 71, 71))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/5.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/5-2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(615, 514, 71, 71))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/6.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/6 (1).png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(779, 514, 71, 71))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/7.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/7-2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(938, 514, 71, 71))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/8.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/8-2.png);\n"
"border: none;\n"
"border-rudes: 9px;}\n"
"")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        LevelsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LevelsWindow)
        QtCore.QMetaObject.connectSlotsByName(LevelsWindow)

    def retranslateUi(self, LevelsWindow):
        _translate = QtCore.QCoreApplication.translate
        LevelsWindow.setWindowTitle(_translate("LevelsWindow", "MainWindow"))
import photos
