# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lvl_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Level3Window(object):
    def setupUi(self, Level3Window):
        Level3Window.setObjectName("Level3Window")
        Level3Window.resize(1450, 1000)
        Level3Window.setStyleSheet("QMainWindow{\n"
"border-image: url(:/newPrefix/photo/fon_lvl.png);\n"
"border-position: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Level3Window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 128, 119))
        self.pushButton.setMinimumSize(QtCore.QSize(128, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(128, 122))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/home.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/home2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 189, 111))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/back.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/back2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1300, 20, 128, 119))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"\n"
"border: none;\n"
"    background-image: url(:/newPrefix/photo/zanovo.png);\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/zanovo2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 50, 551, 61))
        self.label.setStyleSheet("background-image: url(:/newPrefix/photo/уровень.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 860, 338, 77))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/photo/счёт.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1000, 40, 71, 71))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/photo/lvl3.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.circle_2 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_2.setGeometry(QtCore.QRect(470, 270, 49, 52))
        self.circle_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_2.setText("")
        self.circle_2.setObjectName("circle_2")
        self.circle_5 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_5.setGeometry(QtCore.QRect(470, 650, 49, 52))
        self.circle_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_5.setText("")
        self.circle_5.setObjectName("circle_5")
        self.circle_1 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_1.setGeometry(QtCore.QRect(853, 265, 49, 52))
        self.circle_1.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_1.setText("")
        self.circle_1.setObjectName("circle_1")
        self.circle_4 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_4.setGeometry(QtCore.QRect(851, 653, 49, 52))
        self.circle_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_4.setText("")
        self.circle_4.setObjectName("circle_4")
        self.circle_3 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_3.setGeometry(QtCore.QRect(659, 398, 49, 52))
        self.circle_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_3.setText("")
        self.circle_3.setObjectName("circle_3")
        self.circle_6 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_6.setGeometry(QtCore.QRect(661, 739, 49, 52))
        self.circle_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_6.setText("")
        self.circle_6.setObjectName("circle_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(660, 655, 241, 133))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 1.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(470, 270, 241, 179))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 2.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(660, 265, 241, 183))
        self.label_7.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 3.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(657, 396, 243, 307))
        self.label_8.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 5.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(470, 400, 239, 302))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 6.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(470, 653, 241, 138))
        self.label_10.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 7.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(470, 270, 49, 551))
        self.label_11.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 8.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(854, 267, 49, 551))
        self.label_12.setStyleSheet("background-image: url(:/newPrefix/photo/Line3 8.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.circle_8 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_8.setGeometry(QtCore.QRect(470, 770, 49, 52))
        self.circle_8.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_8.setText("")
        self.circle_8.setObjectName("circle_8")
        self.circle_7 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_7.setGeometry(QtCore.QRect(854, 768, 49, 52))
        self.circle_7.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_7.setText("")
        self.circle_7.setObjectName("circle_7")
        self.label_12.raise_()
        self.label_11.raise_()
        self.label_10.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.circle_2.raise_()
        self.circle_5.raise_()
        self.circle_1.raise_()
        self.circle_4.raise_()
        self.circle_3.raise_()
        self.circle_6.raise_()
        self.circle_8.raise_()
        self.circle_7.raise_()
        Level3Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Level3Window)
        QtCore.QMetaObject.connectSlotsByName(Level3Window)

    def retranslateUi(self, Level3Window):
        _translate = QtCore.QCoreApplication.translate
        Level3Window.setWindowTitle(_translate("Level3Window", "MainWindow"))
import photos
