# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lvl_7.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Level7Window(object):
    def setupUi(self, Level7Window):
        Level7Window.setObjectName("Level7Window")
        Level7Window.resize(1450, 1000)
        Level7Window.setStyleSheet("QMainWindow{\n"
"border-image: url(:/newPrefix/photo/fon_lvl.png);\n"
"border-position: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Level7Window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 128, 119))
        self.pushButton.setMinimumSize(QtCore.QSize(128, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(128, 122))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/home.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/home2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 189, 111))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/back.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/back2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.restart_btn = QtWidgets.QPushButton(self.centralwidget)
        self.restart_btn.setGeometry(QtCore.QRect(1300, 20, 128, 119))
        self.restart_btn.setStyleSheet("QPushButton{\n"
"\n"
"border: none;\n"
"    background-image: url(:/newPrefix/photo/zanovo.png);\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/zanovo2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.restart_btn.setText("")
        self.restart_btn.setObjectName("restart_btn")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 50, 551, 61))
        self.label.setStyleSheet("background-image: url(:/newPrefix/photo/уровень.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 860, 338, 77))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/photo/счёт.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1010, 40, 71, 71))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/photo/lvl7.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(694, 308, 321, 421))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 1.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.circle_8 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_8.setGeometry(QtCore.QRect(425, 680, 49, 52))
        self.circle_8.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_8.setText("")
        self.circle_8.setObjectName("circle_8")
        self.circle_7 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_7.setGeometry(QtCore.QRect(560, 500, 49, 52))
        self.circle_7.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_7.setText("")
        self.circle_7.setObjectName("circle_7")
        self.circle_5 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_5.setGeometry(QtCore.QRect(700, 680, 49, 52))
        self.circle_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_5.setText("")
        self.circle_5.setObjectName("circle_5")
        self.circle_3 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_3.setGeometry(QtCore.QRect(967, 680, 49, 52))
        self.circle_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_3.setText("")
        self.circle_3.setObjectName("circle_3")
        self.circle_2 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_2.setGeometry(QtCore.QRect(839, 501, 49, 52))
        self.circle_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_2.setText("")
        self.circle_2.setObjectName("circle_2")
        self.circle_1 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_1.setGeometry(QtCore.QRect(694, 308, 49, 52))
        self.circle_1.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_1.setText("")
        self.circle_1.setObjectName("circle_1")
        self.circle_4 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_4.setGeometry(QtCore.QRect(749, 769, 49, 52))
        self.circle_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_4.setText("")
        self.circle_4.setObjectName("circle_4")
        self.circle_6 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_6.setGeometry(QtCore.QRect(655, 768, 49, 52))
        self.circle_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_6.setText("")
        self.circle_6.setObjectName("circle_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(424, 310, 321, 421))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 2.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(703, 500, 184, 231))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 3.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(655, 310, 87, 506))
        self.label_7.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 4.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(694, 310, 103, 508))
        self.label_8.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 5.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(560, 500, 191, 232))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 6.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(426, 680, 319, 51))
        self.label_10.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 7.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(698, 680, 319, 51))
        self.label_12.setStyleSheet("background-image: url(:/newPrefix/photo/Line7 8.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_12.raise_()
        self.label_5.raise_()
        self.label_10.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_8.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.restart_btn.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.circle_8.raise_()
        self.circle_7.raise_()
        self.circle_5.raise_()
        self.circle_3.raise_()
        self.circle_2.raise_()
        self.circle_1.raise_()
        self.circle_4.raise_()
        self.circle_6.raise_()
        Level7Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Level7Window)
        QtCore.QMetaObject.connectSlotsByName(Level7Window)

    def retranslateUi(self, Level7Window):
        _translate = QtCore.QCoreApplication.translate
        Level7Window.setWindowTitle(_translate("Level7Window", "MainWindow"))
import photos
