# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lvl_6.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Level6Window(object):
    def setupUi(self, Level6Window):
        Level6Window.setObjectName("Level6Window")
        Level6Window.resize(1450, 1000)
        Level6Window.setStyleSheet("QMainWindow{\n"
"border-image: url(:/newPrefix/photo/fon_lvl.png);\n"
"border-position: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Level6Window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 128, 119))
        self.pushButton.setMinimumSize(QtCore.QSize(128, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(128, 122))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/home.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/home2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 189, 111))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/back.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/back2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1300, 20, 128, 119))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"\n"
"border: none;\n"
"    background-image: url(:/newPrefix/photo/zanovo.png);\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/zanovo2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 50, 551, 61))
        self.label.setStyleSheet("background-image: url(:/newPrefix/photo/уровень.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 860, 338, 77))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/photo/счёт.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1010, 40, 71, 71))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/photo/lvl6.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.circle_7 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_7.setGeometry(QtCore.QRect(490, 790, 49, 52))
        self.circle_7.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_7.setText("")
        self.circle_7.setObjectName("circle_7")
        self.circle_2 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_2.setGeometry(QtCore.QRect(913, 408, 49, 52))
        self.circle_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_2.setText("")
        self.circle_2.setObjectName("circle_2")
        self.circle_4 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_4.setGeometry(QtCore.QRect(890, 790, 49, 52))
        self.circle_4.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_4.setText("")
        self.circle_4.setObjectName("circle_4")
        self.circle_9 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_9.setGeometry(QtCore.QRect(468, 404, 49, 52))
        self.circle_9.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_9.setText("")
        self.circle_9.setObjectName("circle_9")
        self.circle_1 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_1.setGeometry(QtCore.QRect(690, 269, 49, 52))
        self.circle_1.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_1.setText("")
        self.circle_1.setObjectName("circle_1")
        self.circle_6 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_6.setGeometry(QtCore.QRect(691, 488, 49, 52))
        self.circle_6.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_6.setText("")
        self.circle_6.setObjectName("circle_6")
        self.circle_8 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_8.setGeometry(QtCore.QRect(468, 718, 49, 52))
        self.circle_8.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_8.setText("")
        self.circle_8.setObjectName("circle_8")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(467, 270, 271, 185))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 1.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(690, 270, 274, 189))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 2.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(490, 270, 249, 571))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 3.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(690, 270, 249, 571))
        self.label_7.setMinimumSize(QtCore.QSize(0, 0))
        self.label_7.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 4.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(490, 489, 249, 356))
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 5.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(468, 627, 274, 143))
        self.label_9.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 6.png);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(692, 625, 266, 146))
        self.label_10.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 7.png);")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(690, 490, 251, 353))
        self.label_11.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 8.png);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(910, 410, 49, 359))
        self.label_12.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 9.png);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(468, 407, 49, 360))
        self.label_13.setStyleSheet("background-image: url(:/newPrefix/photo/Line6 10.png);")
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.circle_3 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_3.setGeometry(QtCore.QRect(910, 720, 49, 52))
        self.circle_3.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_3.setText("")
        self.circle_3.setObjectName("circle_3")
        self.circle_5 = QtWidgets.QPushButton(self.centralwidget)
        self.circle_5.setGeometry(QtCore.QRect(692, 624, 49, 52))
        self.circle_5.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:disabled{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.circle_5.setText("")
        self.circle_5.setObjectName("circle_5")
        self.label_8.raise_()
        self.label_6.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_12.raise_()
        self.label_11.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.circle_7.raise_()
        self.circle_2.raise_()
        self.circle_4.raise_()
        self.circle_9.raise_()
        self.circle_1.raise_()
        self.circle_6.raise_()
        self.circle_8.raise_()
        self.label_10.raise_()
        self.circle_3.raise_()
        self.circle_5.raise_()
        Level6Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Level6Window)
        QtCore.QMetaObject.connectSlotsByName(Level6Window)

    def retranslateUi(self, Level6Window):
        _translate = QtCore.QCoreApplication.translate
        Level6Window.setWindowTitle(_translate("Level6Window", "MainWindow"))
import photos
