# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lvl_8.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Level8Window(object):
    def setupUi(self, Level8Window):
        Level8Window.setObjectName("Level8Window")
        Level8Window.resize(1450, 1000)
        Level8Window.setStyleSheet("QMainWindow{\n"
"border-image: url(:/newPrefix/photo/fon_lvl.png);\n"
"border-position: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Level8Window)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 128, 119))
        self.pushButton.setMinimumSize(QtCore.QSize(128, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(128, 122))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/home.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/home2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 189, 111))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/back.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/back2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1300, 20, 128, 119))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"\n"
"border: none;\n"
"    background-image: url(:/newPrefix/photo/zanovo.png);\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/zanovo2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(1300, 150, 128, 119))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border: none;\n"
"    background-image: url(:/newPrefix/photo/otmena.png);\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/otmena2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 50, 551, 61))
        self.label.setStyleSheet("background-image: url(:/newPrefix/photo/уровень.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(420, 860, 338, 77))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/photo/счёт.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1010, 40, 71, 71))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/photo/lvl8.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(480, 330, 549, 419))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/photo/figura_8.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(482, 694, 49, 52))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(838, 329, 49, 52))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(629, 510, 49, 52))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(698, 510, 49, 52))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(980, 502, 49, 52))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(840, 700, 49, 52))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(480, 330, 49, 52))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/Ellipse 1.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/Ellipse 2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        Level8Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Level8Window)
        QtCore.QMetaObject.connectSlotsByName(Level8Window)

    def retranslateUi(self, Level8Window):
        _translate = QtCore.QCoreApplication.translate
        Level8Window.setWindowTitle(_translate("Level8Window", "MainWindow"))
import photos
