# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RulesWindow(object):
    def setupUi(self, RulesWindow):
        RulesWindow.setObjectName("RulesWindow")
        RulesWindow.resize(1450, 1000)
        RulesWindow.setStyleSheet("QMainWindow{\n"
"border-image: url(:/newPrefix/photo/pravila.png);\n"
"border-position: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(RulesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 189, 111))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-image: url(:/newPrefix/photo/back.png);\n"
"border: none;\n"
"border-ruds: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"background-image: url(:/newPrefix/photo/back2.png);\n"
"border: none;\n"
"border-ruds: 9px;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        RulesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RulesWindow)
        QtCore.QMetaObject.connectSlotsByName(RulesWindow)

    def retranslateUi(self, RulesWindow):
        _translate = QtCore.QCoreApplication.translate
        RulesWindow.setWindowTitle(_translate("RulesWindow", "MainWindow"))
import photos
